import Settings from "@mui/icons-material/Settings";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">FIT ČVUT</a>
        </h1>

        <p>lalalalla</p>
      </main>

      <footer>footer</footer>
    </div>
  );
}
